"""Add latest_reading_id to sensors table

Revision ID: db1946cbdfc4
Revises: cb4121906d9e
Create Date: 2025-08-09 13:43:01.566018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1946cbdfc4'
down_revision = 'cb4121906d9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_sensor_types_name', table_name='api_sensor_types')
    op.drop_column('api_sensor_types', 'data_type')
    op.drop_column('api_sensor_types', 'is_active')
    op.add_column('api_sensors', sa.Column('latest_reading_id', sa.UUID(), nullable=True))
    op.drop_constraint('api_sensors_device_id_key', 'api_sensors', type_='unique')
    op.drop_index('ix_api_sensors_device_id', table_name='api_sensors')
    op.create_index(op.f('ix_api_sensors_device_id'), 'api_sensors', ['device_id'], unique=True)
    op.create_foreign_key(None, 'api_sensors', 'api_sensor_readings', ['latest_reading_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_sensors', type_='foreignkey')
    op.drop_index(op.f('ix_api_sensors_device_id'), table_name='api_sensors')
    op.create_index('ix_api_sensors_device_id', 'api_sensors', ['device_id'], unique=False)
    op.create_unique_constraint('api_sensors_device_id_key', 'api_sensors', ['device_id'])
    op.drop_column('api_sensors', 'latest_reading_id')
    op.add_column('api_sensor_types', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('api_sensor_types', sa.Column('data_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_api_sensor_types_name', 'api_sensor_types', ['name'], unique=False)
    # ### end Alembic commands ###
